export const VIDEOS_REQUESTED = 'VIDEOS_REQUESTED';
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCESS';
export const VIDEOS_NOT_REQUESTED = 'VIDEOS_NOT_REQUESTED';
export const VIDEOS_ERROR = 'VIDOES_ERROR';